name: secretgarden_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.3
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.0.0
  http: ^1.5.0


  # ✅ Tambahan untuk notifikasi dari atas
  another_flushbar: ^1.10.29

  # ✅ Tambahan untuk font elegan dari Google Fonts
  google_fonts: ^6.1.0
  shared_preferences: ^2.5.3
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  firebase_database: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/Logo_secretgarden.png
